---
- name: Configure Web Servers
  hosts: webservers
  become: yes
  vars:
    domain: techcorp.com
  tasks:
    - name: Install required packages
      apt:
        name: 
          - apache2
          - libapache2-mod-wsgi-py3
          - python3-pip
          - python3-psycopg2
        state: latest
      notify:
        - Restart Apache

    - name: Install Flask
      pip:
        name: flask
        state: latest

    - name: Install Apache
      apt:
        name: apache2
        state: latest
      notify:
        - Restart Apache

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: true

    - name: Enable Apache site
      command: a2ensite {{ domain }}.conf
      notify:
        - Reload Apache

    - name: Create document root
      file:
        path: /var/www/{{ domain }}
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy Flask application
      copy:
        src: files/app.py
        dest: /var/www/{{ domain }}/app.py

    - name: Create templates directory
      file:
        path: /var/www/{{ domain }}/templates
        state: directory

    - name: Copy HTML template
      copy:
        src: templates/index.html
        dest: /var/www/{{ domain }}/templates/index.html

    - name: Configure Apache to serve Flask app
      template:
        src: templates/apache_flask.conf.j2
        dest: /etc/apache2/sites-available/{{ domain }}.conf
      notify:
        - Reload Apache

    - name: Create WSGI file
      copy:
        content: |
          import sys
          sys.path.insert(0, '/var/www/techcorp.com')
          from app import app as application
        dest: /var/www/techcorp.com/app.wsgi
      notify: Restart Apache

    - name: Enable WSGI module
      apache2_module:
        name: wsgi
        state: present
      notify: Restart Apache

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Check if default Apache site exists
      stat:
        path: /etc/apache2/sites-enabled/000-default.conf
      register: default_site

    - name: Disable default Apache site
      command: a2dissite 000-default.conf
      when: default_site.stat.exists
      notify: Reload Apache

    - name: Remove default Apache site configuration
      file:
        path: /etc/apache2/sites-available/000-default.conf
        state: absent
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      systemd:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

- name: Configure Database Server
  hosts: dbservers
  become: yes
  vars:
    postgresql_version: 14
  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: latest

    - name: Ensure PostgreSQL is listening on all interfaces
      lineinfile:
        path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
        regexp: '^listen_addresses\s*='
        line: "listen_addresses = '*'"
      notify: Restart PostgreSQL

    - name: Ensure PostgreSQL is started and enabled
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Configure PostgreSQL
      template:
        src: templates/pg_hba.conf.j2
        dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
      notify:
        - Reload PostgreSQL

    - name: Allow vagrant user to sudo as postgres without password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^vagrant ALL=\(postgres\) NOPASSWD: ALL'
        line: 'vagrant ALL=(postgres) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Ensure postgres group has necessary permissions
      file:
        path: /var/run/postgresql
        state: directory
        group: postgres
        mode: '0775'

    - name: Check if database exists
      command: sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='myapp'"
      register: db_exists
      changed_when: false

    - name: Create a new database
      command: sudo -u postgres createdb myapp
      when: db_exists.stdout == ""

    - name: Check if user exists
      command: sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='myapp'"
      register: user_exists
      changed_when: false

    - name: Create a new PostgreSQL user
      command: sudo -u postgres psql -c "CREATE USER myapp WITH PASSWORD 'myapppassword';"
      when: user_exists.stdout == ""

    - name: Grant privileges to myapp user
      become_user: postgres
      postgresql_privs:
        type: table
        database: myapp
        roles: myapp
        privs: ALL
        objs: items
        state: present

    - name: Grant schema privileges to myapp user
      become_user: postgres
      postgresql_privs:
        type: schema
        database: myapp
        roles: myapp
        privs: ALL
        objs: public
        state: present

    - name: Create a sample table
      command: sudo -u postgres psql -d myapp -c "CREATE TABLE IF NOT EXISTS items (id serial primary key, name varchar(100));"

    - name: Add unique constraint to name column
      command: >
        sudo -u postgres psql -d myapp -c "
        ALTER TABLE items ADD CONSTRAINT items_name_key UNIQUE (name);"
      register: alter_table
      changed_when: alter_table.rc == 0
      failed_when: 
        - alter_table.rc != 0
        - "'already exists' not in alter_table.stderr"

    - name: Insert sample data
      command: >
        sudo -u postgres psql -d myapp -c "
        INSERT INTO items (name)
        VALUES ('Computers'), ('iPads'), ('iPhones'), ('Android Phones')
        ON CONFLICT (name) DO NOTHING;"

    - name: Verify inserted data
      command: sudo -u postgres psql -d myapp -c "SELECT * FROM items;"
      register: select_result
      changed_when: false

    - name: Display inserted data
      debug:
        var: select_result.stdout_lines

    - name: Verify permissions
      become_user: postgres
      postgresql_query:
        db: myapp
        query: "SELECT grantee, privilege_type FROM information_schema.role_table_grants WHERE table_name='items' AND grantee='myapp';"
      register: permission_check

    - name: Display permission check results
      debug:
        var: permission_check.query_result

  handlers:
    - name: Reload PostgreSQL
      service:
        name: postgresql
        state: reloaded

    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted

- name: Test Web Application
  hosts: webservers
  become: yes
  tasks:
    - name: Ensure Apache is restarted
      meta: flush_handlers

    - name: Wait for Apache to start
      wait_for:
        port: 80
        delay: 5
        timeout: 30

    - name: Fetch webpage content
      uri:
        url: "http://localhost"
        return_content: yes
      register: webpage
      ignore_errors: yes

    - name: Display webpage content
      debug:
        var: webpage.content
      tags: test_flask
